name: Build and deploy Python app to Azure Web App - XVDicom

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'  # Adjust according to your compatibility

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
   #   - name: Run tests
   #     run: |
   #       source venv/bin/activate
   #       pytest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F50D8EE5E10F43018329284E0DDA61A1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9F4E7ABA77D04E80970487AC92EA638A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74A50D0B14F447A7921B0772335D1591 }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'XVDicom'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'  # Deploys the entire current working directory

      - name: Notify deployment status
        run: echo "Deployment to Production completed"
